server:
  port: ${SERVER_PORT:4000}

spring:
  rabbitmq:
    addresses: ${RABBITMQ_URL}

logging:
  level:
    org.springframework.amqp.listener.ConditionalRejectingErrorHandler: error

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:900}
  auth:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}

agencia:
  id: ${AGENCIA_ID:0} # instância em execução

agencia-routing:
  agencias:
    - id: 0
      name: "Nubank"
    - id: 1
      name: "Itau"
    - id: 2
      name: "Bradesco"