server:
  port: ${SERVER_PORT:4000}

agencia:
  id: ${AGENCIA_ID:0} # instância em execução

agencia-routing:
  host: "localhost"
  basePort: 4000
  agencias:
    - id: 0
      name: "Nubank"
    - id: 1
      name: "Itau"
    - id: 2
      name: "Bradesco"